# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import datamovement_pb2 as datamovement__pb2


class DataMoverStub(object):
    """DataMover service definition describes the API for perform data movement
    for NNF storage. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/datamovement.DataMover/Create',
                request_serializer=datamovement__pb2.DataMovementCreateRequest.SerializeToString,
                response_deserializer=datamovement__pb2.DataMovementCreateResponse.FromString,
                )
        self.Status = channel.unary_unary(
                '/datamovement.DataMover/Status',
                request_serializer=datamovement__pb2.DataMovementStatusRequest.SerializeToString,
                response_deserializer=datamovement__pb2.DataMovementStatusResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/datamovement.DataMover/Delete',
                request_serializer=datamovement__pb2.DataMovementDeleteRequest.SerializeToString,
                response_deserializer=datamovement__pb2.DataMovementDeleteResponse.FromString,
                )


class DataMoverServicer(object):
    """DataMover service definition describes the API for perform data movement
    for NNF storage. 
    """

    def Create(self, request, context):
        """Create sends a new data movement request identified by source and destination fields. It returns
        a response containing a unique identifier which can be used to query the status of the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Status requests the status of a previously submitted data movement request. It accepts a unique
        identifier that identifies the request and returns a status message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete will attempt to delete a completed data movement request. It accepts a unique identifer
        that identifies the request and returns the status of the delete operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataMoverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=datamovement__pb2.DataMovementCreateRequest.FromString,
                    response_serializer=datamovement__pb2.DataMovementCreateResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=datamovement__pb2.DataMovementStatusRequest.FromString,
                    response_serializer=datamovement__pb2.DataMovementStatusResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=datamovement__pb2.DataMovementDeleteRequest.FromString,
                    response_serializer=datamovement__pb2.DataMovementDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datamovement.DataMover', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataMover(object):
    """DataMover service definition describes the API for perform data movement
    for NNF storage. 
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datamovement.DataMover/Create',
            datamovement__pb2.DataMovementCreateRequest.SerializeToString,
            datamovement__pb2.DataMovementCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datamovement.DataMover/Status',
            datamovement__pb2.DataMovementStatusRequest.SerializeToString,
            datamovement__pb2.DataMovementStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datamovement.DataMover/Delete',
            datamovement__pb2.DataMovementDeleteRequest.SerializeToString,
            datamovement__pb2.DataMovementDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
