# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import datamovement_pb2 as datamovement__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DataMoverStub(object):
    """DataMover service definition describes the API for perform data movement
    for NNF storage. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Version = channel.unary_unary(
                '/datamovement.DataMover/Version',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=datamovement__pb2.DataMovementVersionResponse.FromString,
                )
        self.Create = channel.unary_unary(
                '/datamovement.DataMover/Create',
                request_serializer=datamovement__pb2.DataMovementCreateRequest.SerializeToString,
                response_deserializer=datamovement__pb2.DataMovementCreateResponse.FromString,
                )
        self.Status = channel.unary_unary(
                '/datamovement.DataMover/Status',
                request_serializer=datamovement__pb2.DataMovementStatusRequest.SerializeToString,
                response_deserializer=datamovement__pb2.DataMovementStatusResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/datamovement.DataMover/Delete',
                request_serializer=datamovement__pb2.DataMovementDeleteRequest.SerializeToString,
                response_deserializer=datamovement__pb2.DataMovementDeleteResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/datamovement.DataMover/List',
                request_serializer=datamovement__pb2.DataMovementListRequest.SerializeToString,
                response_deserializer=datamovement__pb2.DataMovementListResponse.FromString,
                )
        self.Cancel = channel.unary_unary(
                '/datamovement.DataMover/Cancel',
                request_serializer=datamovement__pb2.DataMovementCancelRequest.SerializeToString,
                response_deserializer=datamovement__pb2.DataMovementCancelResponse.FromString,
                )


class DataMoverServicer(object):
    """DataMover service definition describes the API for perform data movement
    for NNF storage. 
    """

    def Version(self, request, context):
        """Version sends a request to the data movement daemon and returns a response containing
        details on the current build version and supported API versions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Create sends a new data movement request identified by source and destination fields. It returns
        a response containing a unique identifier which can be used to query the status of the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Status requests the status of a previously submitted data movement request. It accepts a unique
        identifier that identifies the request and returns a status message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete will attempt to delete a completed data movement request. It accepts a unique identifier
        that identifies the request and returns the status of the delete operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List returns all current data movement requests for a given namespace and workflow.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Cancel will attempt to stop a data movement request. It accepts a unique identifier
        that identifies the request and returns the status of the cancel operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataMoverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=datamovement__pb2.DataMovementVersionResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=datamovement__pb2.DataMovementCreateRequest.FromString,
                    response_serializer=datamovement__pb2.DataMovementCreateResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=datamovement__pb2.DataMovementStatusRequest.FromString,
                    response_serializer=datamovement__pb2.DataMovementStatusResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=datamovement__pb2.DataMovementDeleteRequest.FromString,
                    response_serializer=datamovement__pb2.DataMovementDeleteResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=datamovement__pb2.DataMovementListRequest.FromString,
                    response_serializer=datamovement__pb2.DataMovementListResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=datamovement__pb2.DataMovementCancelRequest.FromString,
                    response_serializer=datamovement__pb2.DataMovementCancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datamovement.DataMover', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataMover(object):
    """DataMover service definition describes the API for perform data movement
    for NNF storage. 
    """

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datamovement.DataMover/Version',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            datamovement__pb2.DataMovementVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datamovement.DataMover/Create',
            datamovement__pb2.DataMovementCreateRequest.SerializeToString,
            datamovement__pb2.DataMovementCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datamovement.DataMover/Status',
            datamovement__pb2.DataMovementStatusRequest.SerializeToString,
            datamovement__pb2.DataMovementStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datamovement.DataMover/Delete',
            datamovement__pb2.DataMovementDeleteRequest.SerializeToString,
            datamovement__pb2.DataMovementDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datamovement.DataMover/List',
            datamovement__pb2.DataMovementListRequest.SerializeToString,
            datamovement__pb2.DataMovementListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datamovement.DataMover/Cancel',
            datamovement__pb2.DataMovementCancelRequest.SerializeToString,
            datamovement__pb2.DataMovementCancelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
