# Copyright 2024-2025 Hewlett Packard Enterprise Development LP
# Other additional copyright holders may be indicated within.
#
# The entirety of this work is licensed under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
#
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Use rocky 8.10 to get a similar environment as TOSS 4.8.
FROM rockylinux/rockylinux:8.10 AS builder

WORKDIR /workspace

RUN dnf install -y \
    make gcc libcurl-devel json-c json-c-devel

COPY daemons/lib-copy-offload daemons/lib-copy-offload/
COPY Makefile Makefile

RUN CC=gcc make -C ./daemons/lib-copy-offload tester

FROM scratch AS artifacts
COPY --from=builder /workspace/daemons/lib-copy-offload/tester /
