# Copyright 2024-2025 Hewlett Packard Enterprise Development LP
# Other additional copyright holders may be indicated within.
#
# The entirety of this work is licensed under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
#
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$BUILDPLATFORM gcc:12.4.0-bookworm AS builder

WORKDIR /workspace

COPY daemons/lib-copy-offload daemons/lib-copy-offload/
COPY Makefile Makefile

RUN wget http://http.us.debian.org/debian/pool/main/j/json-c/libjson-c-dev_0.16-2_arm64.deb && \
    wget http://http.us.debian.org/debian/pool/main/j/json-c/libjson-c5_0.16-2_arm64.deb && \
    apt-get install ./libjson-c-dev_0.16-2_arm64.deb ./libjson-c5_0.16-2_arm64.deb

RUN CC=gcc make -C ./daemons/lib-copy-offload tester

FROM scratch AS artifacts
COPY --from=builder /workspace/daemons/lib-copy-offload/tester /
