kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: /tmp/nnf
    containerPath: /mnt
    propagation: None
- role: worker
  extraMounts:
  - hostPath: /tmp/nnf
    containerPath: /mnt
    propagation: None
