resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

#patches:
#- path: manager_imagepullsecret_patch.yaml

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newTag: 0.1.6
- name: nnf-mfu
  newTag: 0.1.2
