apiVersion: dm.cray.hpe.com/v1alpha1
kind: RsyncTemplate
metadata:
  name: rsynctemplate-sample
spec:
  selectors:
    matchLabels:
      cray.nnf.node: "true"
  template:
    spec:
    - containers:
      name: rsync-controller
      image: arti.dev.cray.com/rabsw-docker-stable-local/nnf-dm:latest
      command: /manager
      args:
      - --controller=node
      env:
      - name: NNF_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName

