apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
data:
  sshd_config: |
    Include /etc/ssh/sshd_config.d/*.conf
    Port 2222
    StrictModes no
    MaxSessions 4096
    MaxStartups 4096
    ChallengeResponseAuthentication no
    UsePAM yes
    X11Forwarding yes
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem sftp /usr/lib/openssh/sftp-server
