apiVersion: v1
kind: ServiceAccount
metadata:
  name: copy-offload
  namespace: default
---
# As of Kubernetes 1.24, ServiceAccount tokens are no longer automatically
# generated. Instead, manually create the secret and the token key in the
# data field will be automatically set.
apiVersion: v1
kind: Secret
metadata:
  name: copy-offload
  namespace: default
  annotations:
    kubernetes.io/service-account.name: copy-offload
    kubernetes.io/service-account.namespace: default
type: kubernetes.io/service-account-token
