# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: nnf-dm-

resources:
- copy_offload_service_account.yaml
- copy_offload_role.yaml
- copy_offload_role_binding.yaml

configurations:
  - kustomizeconfig.yaml
