// TODO: Copyright

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: api/rsyncdatamovement.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RsyncDataMovementStatusResponse_State int32

const (
	RsyncDataMovementStatusResponse_PENDING       RsyncDataMovementStatusResponse_State = 0
	RsyncDataMovementStatusResponse_STARTING      RsyncDataMovementStatusResponse_State = 1
	RsyncDataMovementStatusResponse_RUNNING       RsyncDataMovementStatusResponse_State = 2
	RsyncDataMovementStatusResponse_COMPLETED     RsyncDataMovementStatusResponse_State = 3
	RsyncDataMovementStatusResponse_UNKNOWN_STATE RsyncDataMovementStatusResponse_State = 4
)

// Enum value maps for RsyncDataMovementStatusResponse_State.
var (
	RsyncDataMovementStatusResponse_State_name = map[int32]string{
		0: "PENDING",
		1: "STARTING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "UNKNOWN_STATE",
	}
	RsyncDataMovementStatusResponse_State_value = map[string]int32{
		"PENDING":       0,
		"STARTING":      1,
		"RUNNING":       2,
		"COMPLETED":     3,
		"UNKNOWN_STATE": 4,
	}
)

func (x RsyncDataMovementStatusResponse_State) Enum() *RsyncDataMovementStatusResponse_State {
	p := new(RsyncDataMovementStatusResponse_State)
	*p = x
	return p
}

func (x RsyncDataMovementStatusResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RsyncDataMovementStatusResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rsyncdatamovement_proto_enumTypes[0].Descriptor()
}

func (RsyncDataMovementStatusResponse_State) Type() protoreflect.EnumType {
	return &file_api_rsyncdatamovement_proto_enumTypes[0]
}

func (x RsyncDataMovementStatusResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RsyncDataMovementStatusResponse_State.Descriptor instead.
func (RsyncDataMovementStatusResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_api_rsyncdatamovement_proto_rawDescGZIP(), []int{3, 0}
}

type RsyncDataMovementStatusResponse_Status int32

const (
	RsyncDataMovementStatusResponse_INVALID        RsyncDataMovementStatusResponse_Status = 0
	RsyncDataMovementStatusResponse_NOT_FOUND      RsyncDataMovementStatusResponse_Status = 1
	RsyncDataMovementStatusResponse_SUCCESS        RsyncDataMovementStatusResponse_Status = 2
	RsyncDataMovementStatusResponse_FAILED         RsyncDataMovementStatusResponse_Status = 3
	RsyncDataMovementStatusResponse_UNKNOWN_STATUS RsyncDataMovementStatusResponse_Status = 4
)

// Enum value maps for RsyncDataMovementStatusResponse_Status.
var (
	RsyncDataMovementStatusResponse_Status_name = map[int32]string{
		0: "INVALID",
		1: "NOT_FOUND",
		2: "SUCCESS",
		3: "FAILED",
		4: "UNKNOWN_STATUS",
	}
	RsyncDataMovementStatusResponse_Status_value = map[string]int32{
		"INVALID":        0,
		"NOT_FOUND":      1,
		"SUCCESS":        2,
		"FAILED":         3,
		"UNKNOWN_STATUS": 4,
	}
)

func (x RsyncDataMovementStatusResponse_Status) Enum() *RsyncDataMovementStatusResponse_Status {
	p := new(RsyncDataMovementStatusResponse_Status)
	*p = x
	return p
}

func (x RsyncDataMovementStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RsyncDataMovementStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rsyncdatamovement_proto_enumTypes[1].Descriptor()
}

func (RsyncDataMovementStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_api_rsyncdatamovement_proto_enumTypes[1]
}

func (x RsyncDataMovementStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RsyncDataMovementStatusResponse_Status.Descriptor instead.
func (RsyncDataMovementStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_rsyncdatamovement_proto_rawDescGZIP(), []int{3, 1}
}

type RsyncDataMovementDeleteResponse_Status int32

const (
	RsyncDataMovementDeleteResponse_INVALID   RsyncDataMovementDeleteResponse_Status = 0
	RsyncDataMovementDeleteResponse_NOT_FOUND RsyncDataMovementDeleteResponse_Status = 1
	RsyncDataMovementDeleteResponse_DELETED   RsyncDataMovementDeleteResponse_Status = 2
	RsyncDataMovementDeleteResponse_ACTIVE    RsyncDataMovementDeleteResponse_Status = 3
	RsyncDataMovementDeleteResponse_UNKNOWN   RsyncDataMovementDeleteResponse_Status = 4
)

// Enum value maps for RsyncDataMovementDeleteResponse_Status.
var (
	RsyncDataMovementDeleteResponse_Status_name = map[int32]string{
		0: "INVALID",
		1: "NOT_FOUND",
		2: "DELETED",
		3: "ACTIVE",
		4: "UNKNOWN",
	}
	RsyncDataMovementDeleteResponse_Status_value = map[string]int32{
		"INVALID":   0,
		"NOT_FOUND": 1,
		"DELETED":   2,
		"ACTIVE":    3,
		"UNKNOWN":   4,
	}
)

func (x RsyncDataMovementDeleteResponse_Status) Enum() *RsyncDataMovementDeleteResponse_Status {
	p := new(RsyncDataMovementDeleteResponse_Status)
	*p = x
	return p
}

func (x RsyncDataMovementDeleteResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RsyncDataMovementDeleteResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rsyncdatamovement_proto_enumTypes[2].Descriptor()
}

func (RsyncDataMovementDeleteResponse_Status) Type() protoreflect.EnumType {
	return &file_api_rsyncdatamovement_proto_enumTypes[2]
}

func (x RsyncDataMovementDeleteResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RsyncDataMovementDeleteResponse_Status.Descriptor instead.
func (RsyncDataMovementDeleteResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_rsyncdatamovement_proto_rawDescGZIP(), []int{5, 0}
}

// The data movemement create request message containing the source and destination files or directories. The
// NNF Data Mover will perform a copy from source to the destination. Specify dryrun to instantiate
// a new data movement request where the copy is simulated and not executed
type RsyncDataMovementCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Initiator   string `protobuf:"bytes,1,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Target      string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Workflow    string `protobuf:"bytes,3,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Namespace   string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Source      string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Destination string `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	Dryrun      bool   `protobuf:"varint,7,opt,name=dryrun,proto3" json:"dryrun,omitempty"`
}

func (x *RsyncDataMovementCreateRequest) Reset() {
	*x = RsyncDataMovementCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rsyncdatamovement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncDataMovementCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncDataMovementCreateRequest) ProtoMessage() {}

func (x *RsyncDataMovementCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rsyncdatamovement_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncDataMovementCreateRequest.ProtoReflect.Descriptor instead.
func (*RsyncDataMovementCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_rsyncdatamovement_proto_rawDescGZIP(), []int{0}
}

func (x *RsyncDataMovementCreateRequest) GetInitiator() string {
	if x != nil {
		return x.Initiator
	}
	return ""
}

func (x *RsyncDataMovementCreateRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RsyncDataMovementCreateRequest) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *RsyncDataMovementCreateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RsyncDataMovementCreateRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RsyncDataMovementCreateRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RsyncDataMovementCreateRequest) GetDryrun() bool {
	if x != nil {
		return x.Dryrun
	}
	return false
}

// The data movement create response message contains a unique identifier amont all data movement requests for
// the lifetime of the active job. The UID can be used to query for status of the request using the
// data movememnt status request message.
type RsyncDataMovementCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *RsyncDataMovementCreateResponse) Reset() {
	*x = RsyncDataMovementCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rsyncdatamovement_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncDataMovementCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncDataMovementCreateResponse) ProtoMessage() {}

func (x *RsyncDataMovementCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rsyncdatamovement_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncDataMovementCreateResponse.ProtoReflect.Descriptor instead.
func (*RsyncDataMovementCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_rsyncdatamovement_proto_rawDescGZIP(), []int{1}
}

func (x *RsyncDataMovementCreateResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// The data movement status request message permits users to query the status of a previously issued
// data movement request by specifying the request's unique identifier.
type RsyncDataMovementStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *RsyncDataMovementStatusRequest) Reset() {
	*x = RsyncDataMovementStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rsyncdatamovement_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncDataMovementStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncDataMovementStatusRequest) ProtoMessage() {}

func (x *RsyncDataMovementStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rsyncdatamovement_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncDataMovementStatusRequest.ProtoReflect.Descriptor instead.
func (*RsyncDataMovementStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_rsyncdatamovement_proto_rawDescGZIP(), []int{2}
}

func (x *RsyncDataMovementStatusRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// The data movement status response message defines the current status of a data movement request. The
// state field describes the current state of the request. The message field contains ancillary information
// describing the data movement request.
type RsyncDataMovementStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State   RsyncDataMovementStatusResponse_State  `protobuf:"varint,1,opt,name=state,proto3,enum=datamovement.RsyncDataMovementStatusResponse_State" json:"state,omitempty"`
	Status  RsyncDataMovementStatusResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=datamovement.RsyncDataMovementStatusResponse_Status" json:"status,omitempty"`
	Message string                                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RsyncDataMovementStatusResponse) Reset() {
	*x = RsyncDataMovementStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rsyncdatamovement_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncDataMovementStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncDataMovementStatusResponse) ProtoMessage() {}

func (x *RsyncDataMovementStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rsyncdatamovement_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncDataMovementStatusResponse.ProtoReflect.Descriptor instead.
func (*RsyncDataMovementStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_rsyncdatamovement_proto_rawDescGZIP(), []int{3}
}

func (x *RsyncDataMovementStatusResponse) GetState() RsyncDataMovementStatusResponse_State {
	if x != nil {
		return x.State
	}
	return RsyncDataMovementStatusResponse_PENDING
}

func (x *RsyncDataMovementStatusResponse) GetStatus() RsyncDataMovementStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return RsyncDataMovementStatusResponse_INVALID
}

func (x *RsyncDataMovementStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The data movement delete request permits users to delete a completed data movement request (any request with a
// status of COMPLETED) by specifying the request's unique identifier.
type RsyncDataMovementDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *RsyncDataMovementDeleteRequest) Reset() {
	*x = RsyncDataMovementDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rsyncdatamovement_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncDataMovementDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncDataMovementDeleteRequest) ProtoMessage() {}

func (x *RsyncDataMovementDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rsyncdatamovement_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncDataMovementDeleteRequest.ProtoReflect.Descriptor instead.
func (*RsyncDataMovementDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_rsyncdatamovement_proto_rawDescGZIP(), []int{4}
}

func (x *RsyncDataMovementDeleteRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// The data movement delete response returns the status of the delete operation.
type RsyncDataMovementDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status RsyncDataMovementDeleteResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=datamovement.RsyncDataMovementDeleteResponse_Status" json:"status,omitempty"`
}

func (x *RsyncDataMovementDeleteResponse) Reset() {
	*x = RsyncDataMovementDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rsyncdatamovement_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncDataMovementDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncDataMovementDeleteResponse) ProtoMessage() {}

func (x *RsyncDataMovementDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rsyncdatamovement_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncDataMovementDeleteResponse.ProtoReflect.Descriptor instead.
func (*RsyncDataMovementDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_rsyncdatamovement_proto_rawDescGZIP(), []int{5}
}

func (x *RsyncDataMovementDeleteResponse) GetStatus() RsyncDataMovementDeleteResponse_Status {
	if x != nil {
		return x.Status
	}
	return RsyncDataMovementDeleteResponse_INVALID
}

var File_api_rsyncdatamovement_proto protoreflect.FileDescriptor

var file_api_rsyncdatamovement_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x61, 0x74, 0x61, 0x6d,
	0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64,
	0x61, 0x74, 0x61, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xe2, 0x01, 0x0a, 0x1e,
	0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x79, 0x72,
	0x75, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x72, 0x79, 0x72, 0x75, 0x6e,
	0x22, 0x33, 0x0a, 0x1f, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x1e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61,
	0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xfa, 0x02, 0x0a, 0x1f, 0x52, 0x73,
	0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x73, 0x79, 0x6e,
	0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d,
	0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x51, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03,
	0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x10, 0x04, 0x22, 0x51, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a,
	0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f,
	0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44,
	0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x10, 0x04, 0x22, 0x32, 0x0a, 0x1e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xbb, 0x01, 0x0a, 0x1f, 0x52,
	0x73, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x73,
	0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4a, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x04, 0x32, 0xcb, 0x02, 0x0a, 0x0e, 0x52, 0x73, 0x79,
	0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x67, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x76, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x73,
	0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x73, 0x79, 0x6e,
	0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x2c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61,
	0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x6f, 0x76, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x57, 0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x68, 0x70,
	0x65, 0x2e, 0x63, 0x72, 0x61, 0x79, 0x2e, 0x6e, 0x6e, 0x66, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6d,
	0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x11, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x6f, 0x76,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x21, 0x6e, 0x6e,
	0x66, 0x2e, 0x63, 0x72, 0x61, 0x79, 0x2e, 0x68, 0x70, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x61, 0x74, 0x61, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_rsyncdatamovement_proto_rawDescOnce sync.Once
	file_api_rsyncdatamovement_proto_rawDescData = file_api_rsyncdatamovement_proto_rawDesc
)

func file_api_rsyncdatamovement_proto_rawDescGZIP() []byte {
	file_api_rsyncdatamovement_proto_rawDescOnce.Do(func() {
		file_api_rsyncdatamovement_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_rsyncdatamovement_proto_rawDescData)
	})
	return file_api_rsyncdatamovement_proto_rawDescData
}

var file_api_rsyncdatamovement_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_rsyncdatamovement_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_rsyncdatamovement_proto_goTypes = []interface{}{
	(RsyncDataMovementStatusResponse_State)(0),  // 0: datamovement.RsyncDataMovementStatusResponse.State
	(RsyncDataMovementStatusResponse_Status)(0), // 1: datamovement.RsyncDataMovementStatusResponse.Status
	(RsyncDataMovementDeleteResponse_Status)(0), // 2: datamovement.RsyncDataMovementDeleteResponse.Status
	(*RsyncDataMovementCreateRequest)(nil),      // 3: datamovement.RsyncDataMovementCreateRequest
	(*RsyncDataMovementCreateResponse)(nil),     // 4: datamovement.RsyncDataMovementCreateResponse
	(*RsyncDataMovementStatusRequest)(nil),      // 5: datamovement.RsyncDataMovementStatusRequest
	(*RsyncDataMovementStatusResponse)(nil),     // 6: datamovement.RsyncDataMovementStatusResponse
	(*RsyncDataMovementDeleteRequest)(nil),      // 7: datamovement.RsyncDataMovementDeleteRequest
	(*RsyncDataMovementDeleteResponse)(nil),     // 8: datamovement.RsyncDataMovementDeleteResponse
}
var file_api_rsyncdatamovement_proto_depIdxs = []int32{
	0, // 0: datamovement.RsyncDataMovementStatusResponse.state:type_name -> datamovement.RsyncDataMovementStatusResponse.State
	1, // 1: datamovement.RsyncDataMovementStatusResponse.status:type_name -> datamovement.RsyncDataMovementStatusResponse.Status
	2, // 2: datamovement.RsyncDataMovementDeleteResponse.status:type_name -> datamovement.RsyncDataMovementDeleteResponse.Status
	3, // 3: datamovement.RsyncDataMover.Create:input_type -> datamovement.RsyncDataMovementCreateRequest
	5, // 4: datamovement.RsyncDataMover.Status:input_type -> datamovement.RsyncDataMovementStatusRequest
	7, // 5: datamovement.RsyncDataMover.Delete:input_type -> datamovement.RsyncDataMovementDeleteRequest
	4, // 6: datamovement.RsyncDataMover.Create:output_type -> datamovement.RsyncDataMovementCreateResponse
	6, // 7: datamovement.RsyncDataMover.Status:output_type -> datamovement.RsyncDataMovementStatusResponse
	8, // 8: datamovement.RsyncDataMover.Delete:output_type -> datamovement.RsyncDataMovementDeleteResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_rsyncdatamovement_proto_init() }
func file_api_rsyncdatamovement_proto_init() {
	if File_api_rsyncdatamovement_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_rsyncdatamovement_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncDataMovementCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rsyncdatamovement_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncDataMovementCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rsyncdatamovement_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncDataMovementStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rsyncdatamovement_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncDataMovementStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rsyncdatamovement_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncDataMovementDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rsyncdatamovement_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncDataMovementDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_rsyncdatamovement_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rsyncdatamovement_proto_goTypes,
		DependencyIndexes: file_api_rsyncdatamovement_proto_depIdxs,
		EnumInfos:         file_api_rsyncdatamovement_proto_enumTypes,
		MessageInfos:      file_api_rsyncdatamovement_proto_msgTypes,
	}.Build()
	File_api_rsyncdatamovement_proto = out.File
	file_api_rsyncdatamovement_proto_rawDesc = nil
	file_api_rsyncdatamovement_proto_goTypes = nil
	file_api_rsyncdatamovement_proto_depIdxs = nil
}
