---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daemon-role
rules:
- apiGroups:
  - lus.cray.hpe.com
  resources:
  - lustrefilesystems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - workflows
  verbs:
  - get
  - list
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts
  verbs:
  - get
  - list
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts/status
  verbs:
  - get
  - list
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - systemconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovementprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovements/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovements/status
  verbs:
  - get
  - patch
  - update
