# permissions for end users to view datamovements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datamovement-viewer-role
rules:
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - datamovements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - datamovements/status
  verbs:
  - get
