# permissions for end users to view datamovementmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datamovementmanager-viewer-role
rules:
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - datamovementmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - datamovementmanagers/status
  verbs:
  - get
