# permissions for end users to edit datamovementmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datamovementmanager-editor-role
rules:
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - datamovementmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - datamovementmanagers/status
  verbs:
  - get
