# permissions for end users to view rsyncnodedatamovements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rsyncnodedatamovement-viewer-role
rules:
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsyncnodedatamovements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsyncnodedatamovements/status
  verbs:
  - get
