# permissions for end users to edit rsynctemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rsynctemplate-editor-role
rules:
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsynctemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsynctemplates/status
  verbs:
  - get
