# permissions for end users to edit rsyncdatamovements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rsyncdatamovement-editor-role
rules:
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsyncdatamovements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsyncdatamovements/status
  verbs:
  - get
