# permissions for end users to edit rsyncnodedatamovements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rsyncnodedatamovement-editor-role
rules:
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsyncnodedatamovements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsyncnodedatamovements/status
  verbs:
  - get
