# permissions for end users to view rsynctemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rsynctemplate-viewer-role
rules:
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsynctemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsynctemplates/status
  verbs:
  - get
