# permissions for end users to view rsyncdatamovements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rsyncdatamovement-viewer-role
rules:
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsyncdatamovements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dm.cray.hpe.com
  resources:
  - rsyncdatamovements/status
  verbs:
  - get
