apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
---
# As of Kubernetes 1.24, ServiceAccount tokens are no longer automatically
# generated. Instead, manually create the secret and the token key in the
# data field will be automatically set.
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: system
  annotations:
    kubernetes.io/service-account.name: controller-manager
    kubernetes.io/service-account.namespace: system
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-controller
  namespace: system
---
apiVersion: v1
kind: Secret
metadata:
  name: node-controller
  namespace: system
  annotations:
    kubernetes.io/service-account.name: node-controller
    kubernetes.io/service-account.namespace: system
type: kubernetes.io/service-account-token
