apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: ENVIRONMENT
          value: "kind"
