---
apiVersion: nnf.cray.hpe.com/v1alpha4
kind: NnfContainerProfile
metadata:
  name: copy-offload-nonmpi
  namespace: nnf-system
data:
  storages:
    - name: DW_JOB_my_storage
      optional: false
  numPorts: 1
  spec:
    containers:
      - name: copy-offload-srvr
        image: ghcr.io/nearnodeflash/nnf-dm-copy-offload:0.0.0.273-07bf0
        command:
          - /nnf-copy-offload
          - --port
          - $(NNF_CONTAINER_PORTS)
    serviceAccount: nnf-dm-copy-offload
    serviceAccountName: nnf-dm-copy-offload
  retryLimit: 2
---
apiVersion: dataworkflowservices.github.io/v1alpha2
kind: Workflow
metadata:
  name: copy-offload-nonmpi
  namespace: default
spec:
  desiredState: "Proposal"
  dwDirectives:
    - "#DW jobdw name=copyoff-gfs2 type=gfs2 capacity=50GB"
    - "#DW container name=copyoff-container profile=copy-offload-nonmpi \
      DW_JOB_my_storage=copyoff-gfs2"
  wlmID: "Bubbly WLM"
  jobID: "fDeansJob3"
  userID: 1050
  groupID: 1051
