apiVersion: dataworkflowservices.github.io/v1alpha2
kind: Workflow
metadata:
  name: copy-offload-nonmpi
  namespace: default
spec:
  desiredState: "Proposal"
  dwDirectives:
    - "#DW jobdw name=copyoff-gfs2 type=gfs2 capacity=50GB"
    - "#DW container name=copyoff-container profile=copy-offload-nonmpi \
      DW_JOB_my_storage=copyoff-gfs2 DW_GLOBAL_lus=/lus/foo/copyoff"
  wlmID: "Bubbly WLM"
  jobID: "fDeansJob3"
  userID: 1050
  groupID: 1051
