apiVersion: dataworkflowservices.github.io/v1alpha2
kind: Workflow
metadata:
  name: copy-offload-yellow
  namespace: default
spec:
  desiredState: "Proposal"

# The container profile is specified here.
# The datamovement profile is specified in the copy-offload request from
# the client. This is the 'dmProfile' argument.

  dwDirectives:
    - "#DW jobdw name=copyoff-gfs2 type=gfs2 capacity=50GB requires=copy-offload"
    - "#DW container name=copyoff-container profile=copy-offload-default \
      DW_JOB_my_storage=copyoff-gfs2 DW_GLOBAL_lus=/lus/foo/copyoff"
  wlmID: "Bubbly WLM"
  jobID: "fDeansJob3"
  userID: 1050
  groupID: 1051
