apiVersion: dataworkflowservices.github.io/v1alpha3
kind: Workflow
metadata:
  name: copy-offload-blake
  namespace: default
spec:
  desiredState: "Proposal"

# The container profile is specified here.
# The datamovement profile is specified in the copy-offload request from
# the client. This is the 'dmProfile' argument.

#    - "#DW jobdw name=copyoff-gfs2 type=gfs2 capacity=50GB requires=copy-offload"

  dwDirectives:
    - "#DW jobdw name=copyoff-lustre type=lustre capacity=50GB requires=copy-offload"
    - "#DW container name=copyoff-container profile=copy-offload-default \
      DW_JOB_my_storage=copyoff-lustre DW_GLOBAL_lus=/lus/global/copyoff"
  wlmID: "Bubbly WLM"
  jobID: "fBlakesJob3"
  userID: 1060
  groupID: 1061
