---
apiVersion: nnf.cray.hpe.com/v1alpha4
kind: NnfContainerProfile
metadata:
  name: copy-offload-mpi
  namespace: nnf-system
data:
  storages:
    - name: DW_JOB_my_storage
      optional: false
  # $NNF_CONTAINER_PORTS can be used to get the port number(s)
  numPorts: 1
  mpiSpec:
    mpiReplicaSpecs:
      Launcher:
        template:
          spec:
            containers:
              - name: copy-offload-srvr
                image: ghcr.io/nearnodeflash/nnf-dm-copy-offload:0.0.0.267-c4ca
                command:
                  - /nnf-copy-offload
                  - --port=8080
                  # An example webserver can be started using python
                  # - mpirun
                  # - python3
                  # - -m
                  # - http.server
                  # - $(NNF_CONTAINER_PORTS)
                env:
                - name: NNF_NODE_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                ports:
                - containerPort: 8080
                  hostPort: 8080
                  protocol: TCP
            serviceAccount: nnf-dm-copy-offload
            serviceAccountName: nnf-dm-copy-offload
      Worker:
        template:
          spec:
            containers:
              - name: nnf-container-example
                image: ghcr.io/nearnodeflash/nnf-container-example:master
  retryLimit: 2
---
apiVersion: dataworkflowservices.github.io/v1alpha2
kind: Workflow
metadata:
  name: copy-offload-mpi
  namespace: default
spec:
  desiredState: "Proposal"
  dwDirectives:
    - "#DW jobdw name=copyoff-gfs2 type=gfs2 capacity=50GB"
    - "#DW container name=copyoff-container profile=copy-offload-mpi \
      DW_JOB_my_storage=copyoff-gfs2"
  wlmID: "Bubbly WLM"
  jobID: "fDeansJob2"
  userID: 1050
  groupID: 1051
