---
apiVersion: nnf.cray.hpe.com/v1alpha6
kind: NnfContainerProfile
metadata:
  name: copy-offload-template
  namespace: nnf-system
data:
  storages:
    - name: DW_JOB_my_storage
      optional: false
    - name: DW_GLOBAL_lus
      optional: false
  numPorts: 1
  spec:
    containers:
      - name: copy-offload-srvr
        image: ghcr.io/nearnodeflash/nnf-dm-copy-offload:latest
        command:
          - /nnf-copy-offload
          - --cert
          - $(TLS_CERT_PATH)
          - --cakey
          - $(TLS_KEY_PATH)
          - --tokenkey
          - $(TOKEN_KEY_PATH)
          - --addr
          - :$(NNF_CONTAINER_PORTS)
        env:
          # OMPI_MCA_orte_keep_fqdn_hostnames is required for mpirun to be able to communicate with
          # the nnf-dm-worker pods. Normal user containers should not require this environment
          # variable.
          - name: OMPI_MCA_orte_keep_fqdn_hostnames
            value: 'true'
      # TODO inject this from sos when we find the serviceAccount below
      - name: copy-offload-worker
        image: nnf-mfu:latest
        command:
          - /usr/sbin/sshd
        args:
          - -De
        # securityContext:
        #   privileged: true
        #   capabilities:
        #     add: ['SETUID', 'SETGID', 'MKNOD']
        # volumeMounts:
        #   - name:  worker-config
        #     mountPath: /etc/ssh/sshd_config
        #     subPath: sshd_config
        #   - name: localtime
        #     mountPath: /etc/localtime
        #     readOnly: true
        #   - name: tzdata
        #     mountPath: /usr/share/zoneinfo
        #     readOnly: true

    # This ServiceAccount is used by the nnf-dm-copy-offload server to talk to
    # the Kubernetes API server. This ServiceAccount and its Role are
    # defined in config/copy-offload.
    # Normal user containers should not require Kubernetes API server privilege
    # and should not have a service account.
    serviceAccountName: nnf-dm-copy-offload
  retryLimit: 2
