namespace: nnf-system

resources:
- copyoffload-containerprofiles.yaml
- copyoffload-datamovementprofiles.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nnf-dm-copy-offload
  newName: ghcr.io/nearnodeflash/nnf-dm-copy-offload
  newTag: master
