apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: nnf-dm-config
    namespace: nnf-dm-system
    envs:
      - nnf-dm-config.env
