# Each profile is capable of providing different configurations for data movement.
# Note: For now, only the default profile is supported.
profiles:

  # Default profile that is used for all data movement activity.
  default:
      # The number of slots specified in the MPI hostfile. A value less than 1 disables the use
      # of slots in the hostfile.
      slots: 8

      # The number of max_slots specified in the MPI hostfile. A value less than 1 disables the use
      # of max_slots in the hostfile.
      maxSlots: 0

      # The full command to execute data movement. $VARS are replaced by the nnf software. Available
      # $VARS:
      #   HOSTFILE: hostfile that is created and used for mpirun. Contains a list of hosts and the
      #             slots/max_slots for each host. This hostfile is created at `/tmp/<dm-name>/hostfile`
      #   UID: User ID that is inherited from the Workflow
      #   GID: Group ID that is inherited from the Workflow
      #   SRC: source for the data movement
      #   DEST destination for the data movement
      # default: command: mpirun --allow-run-as-root --hostfile $HOSTFILE dcp --progress 1 --uid $UID --gid $GID $SRC $DEST
      command: mpirun --allow-run-as-root --hostfile $HOSTFILE dcp --progress 1 --uid $UID --gid $GID $SRC $DEST

# NnfDataMovement resources have the ability to collect and store the progress percentage and the
# last few lines of output in the CommandStatus field. This number is used for the interval to collect
# the progress data. `dcp --progress N` must be included in the command.
# A value less than 1 disables this functionality.
progressIntervalSeconds: 5